apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: backend
  name: contacts
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: contacts
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: backend
  name: contacts
spec:
  selector:
    matchLabels:
      app: contacts
      application: bank-of-anthos
      environment: development
      team: accounts
      tier: backend
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: contacts
        application: bank-of-anthos
        environment: development
        team: accounts
        tier: backend
    spec:
      containers:
        - env:
            - name: VERSION
              value: v0.6.4
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: accounts-db-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: accounts-db-credentials
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: accounts-db-credentials
            - name: POSTGRES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: db_endpoint
                  name: accounts-db-credentials
            - name: ACCOUNTS_DB_URI
              valueFrom:
                secretKeyRef:
                  key: accounts_db_uri
                  name: accounts-db-credentials
          envFrom:
            - configMapRef:
                name: environment-config
          image: peoples93/contacts:v1.0
          imagePullPolicy: Always
          name: contacts
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.25Gi
              memory: 128Mi
            requests:
              cpu: 100m
              ephemeral-storage: 0.25Gi
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /tmp/.ssh
              name: publickey
              readOnly: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: bank-of-anthos
      terminationGracePeriodSeconds: 5
      volumes:
        - emptyDir: {}
          name: tmp
        - name: publickey
          secret:
            items:
              - key: jwtRS256.key.pub
                path: publickey
            secretName: jwt-key
