name: Contacts Docker Build

on:
  push:
    branches:
      - master
    paths:
      - 'src/accounts/contacts/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/accounts/contacts/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4.1.0
        with:
          path: "src/accounts/contacts/requirements.txt"
      - name: Lint with flake8
        uses: py-actions/flake8@v2
        with:
          path: "src/accounts/contacts"
          args: "--exit-zero"
      - name: Run tests
        run: |
          cd src/accounts/contacts
          PYTHONPATH=$PWD python -m pytest tests/ -v
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          push: true
          context: "src/accounts/contacts"
          file: "src/accounts/contacts/Dockerfile"
          tags: ${{ secrets.DOCKER_USERNAME }}/contacts:latest
