name: Ledgerwriter Docker Build

on:
  push:
    branches:
      - master
    paths:
      - 'src/ledger/ledgerwriter/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/ledger/ledgerwriter/**'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Test
        working-directory: src/ledger/ledgerwriter
        run: mvn clean verify org.jacoco:jacoco-maven-plugin:report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: src/ledger/ledgerwriter/target/surefire-reports/*.xml

      - name: Upload JaCoCo coverage reports 
        uses: actions/upload-artifact@v4.3.3
        with: 
          name: jacoco-report
          path: src/ledger/ledgerwriter/target/site/jacoco

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: src/ledger/ledgerwriter
        run: |
          mvn clean package jib:build \
            -Djib.to.image=docker.io/${{ secrets.DOCKER_USERNAME }}/ledgerwriter:latest \
            -Djib.to.tags=latest
